# Generated by Django 4.2.30 on 2026-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_migrate_qq_bot_to_plugin_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='captcha_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='captcha_key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_captcha_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_captcha_key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_captcha_provider',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='login_captcha_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='login_captcha_key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='login_captcha_provider',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='register_captcha_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='register_captcha_key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='register_captcha_provider',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='captcha_provider',
            field=models.CharField(choices=[('none', '无'), ('tianai', '天爱验证码')], default='none', help_text='选择要启用的验证码提供器', max_length=32, verbose_name='验证码提供器'),
        ),
    ]
