# Generated by Django 4.2.30 on 2026-05-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_systemconfig_captcha_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='captcha_type',
            field=models.CharField(choices=[('SLIDER', '滑块验证'), ('ROTATE', '旋转验证'), ('CONCAT', '滑动还原'), ('WORD_IMAGE_CLICK', '文字点选')], default='SLIDER', help_text='全局默认的验证码类型', max_length=32, verbose_name='默认验证码类型'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='email_captcha_type',
            field=models.CharField(blank=True, choices=[('SLIDER', '滑块验证'), ('ROTATE', '旋转验证'), ('CONCAT', '滑动还原'), ('WORD_IMAGE_CLICK', '文字点选')], help_text='邮箱发送验证码场景的验证码类型（留空则使用默认类型）', max_length=32, null=True, verbose_name='邮箱验证码类型'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='login_captcha_type',
            field=models.CharField(blank=True, choices=[('SLIDER', '滑块验证'), ('ROTATE', '旋转验证'), ('CONCAT', '滑动还原'), ('WORD_IMAGE_CLICK', '文字点选')], help_text='登录场景的验证码类型（留空则使用默认类型）', max_length=32, null=True, verbose_name='登录验证码类型'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='register_captcha_type',
            field=models.CharField(blank=True, choices=[('SLIDER', '滑块验证'), ('ROTATE', '旋转验证'), ('CONCAT', '滑动还原'), ('WORD_IMAGE_CLICK', '文字点选')], help_text='注册场景的验证码类型（留空则使用默认类型）', max_length=32, null=True, verbose_name='注册验证码类型'),
        ),
    ]
