# Generated by Django 4.2.27 on 2026-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_systemconfig_captcha_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="hostname_branding",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='按主机名绑定专用站点名和图标，格式：\n{"host.example.com": {"site_name": "站点名", "site_icon": "/media/branding/icon.svg"}}\n未配置的主机名使用全局默认值',
                verbose_name="主机名品牌绑定",
            ),
        ),
    ]
