# Generated by Django 4.2.27 on 2026-05-31 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0013_systemconfig_hostname_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="站点组的显示名称",
                        max_length=100,
                        verbose_name="站点组名称",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="唯一标识符，用于URL和内部引用",
                        max_length=100,
                        unique=True,
                        verbose_name="标识符",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="站点组的描述信息", verbose_name="描述"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        help_text="该站点组的站点名称，留空则使用全局默认值",
                        max_length=100,
                        verbose_name="站点名称",
                    ),
                ),
                (
                    "site_icon",
                    models.CharField(
                        blank=True,
                        help_text="该站点组的站点图标路径，留空则使用全局默认值",
                        max_length=500,
                        verbose_name="站点图标",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="禁用后该站点组的所有功能将不可用",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="该站点组的管理员，在当前站点组内拥有类似超级管理员的权限",
                        related_name="admin_site_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="站点组管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点组",
                "verbose_name_plural": "站点组",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteGroupHostname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        help_text="HTTP Host头中的主机名（不含端口），如 demo.example.com",
                        max_length=255,
                        unique=True,
                        verbose_name="主机名",
                    ),
                ),
                (
                    "site_group",
                    models.ForeignKey(
                        help_text="该主机名所属的站点组",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostnames",
                        to="dashboard.sitegroup",
                        verbose_name="所属站点组",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点组主机名",
                "verbose_name_plural": "站点组主机名",
                "indexes": [
                    models.Index(
                        fields=["hostname"], name="dashboard_s_hostnam_daee7a_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sitegroup",
            index=models.Index(fields=["slug"], name="dashboard_s_slug_5cb7f5_idx"),
        ),
    ]
