# Generated by Django 4.2.27 on 2026-06-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_sitegroup_sitegrouphostname_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sitegroup",
            name="dashboard_s_slug_5cb7f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="sitegrouphostname",
            name="dashboard_s_hostnam_daee7a_idx",
        ),
    ]
