# Generated by Django 4.2.27 on 2026-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_remove_sitegroup_dashboard_s_slug_5cb7f5_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_from_name",
            field=models.CharField(
                blank=True,
                help_text='系统发送邮件时显示的发件人名称，如"XX云服务"',
                max_length=255,
                null=True,
                verbose_name="发件人名称",
            ),
        ),
    ]
