# Generated by Django 4.2.27 on 2026-06-06 17:56

from django.db import migrations, models


def migrate_smtp_use_tls_to_encryption(apps, schema_editor):
    SystemConfig = apps.get_model('dashboard', 'SystemConfig')
    for config in SystemConfig.objects.all():
        if config.smtp_use_tls:
            config.smtp_encryption = 'TLS'
        else:
            config.smtp_encryption = 'NONE'
        config.save(update_fields=['smtp_encryption'])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_systemconfig_smtp_from_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_encryption",
            field=models.CharField(
                choices=[
                    ("NONE", "无加密"),
                    ("TLS", "TLS (STARTTLS)"),
                    ("SSL", "SSL (SMTPS)"),
                ],
                default="TLS",
                help_text="TLS: 端口通常为587；SSL: 端口通常为465",
                max_length=8,
                verbose_name="加密方式",
            ),
        ),
        migrations.RunPython(
            migrate_smtp_use_tls_to_encryption,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="smtp_use_tls",
        ),
    ]
