# Generated by Django 4.2.27 on 2026-06-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_remove_systemconfig_smtp_use_tls_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteGroupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="留空使用全局配置",
                        max_length=255,
                        null=True,
                        verbose_name="SMTP服务器",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True,
                        help_text="留空使用全局配置",
                        null=True,
                        verbose_name="SMTP端口",
                    ),
                ),
                (
                    "smtp_encryption",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "无加密"),
                            ("TLS", "TLS (STARTTLS)"),
                            ("SSL", "SSL (SMTPS)"),
                        ],
                        help_text="留空使用全局配置",
                        max_length=8,
                        null=True,
                        verbose_name="加密方式",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        help_text="留空使用全局配置",
                        max_length=255,
                        null=True,
                        verbose_name="SMTP用户名",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        help_text="留空使用全局配置",
                        max_length=255,
                        null=True,
                        verbose_name="SMTP密码",
                    ),
                ),
                (
                    "smtp_from_email",
                    models.EmailField(
                        blank=True,
                        help_text="留空使用全局配置",
                        max_length=254,
                        null=True,
                        verbose_name="发件人邮箱",
                    ),
                ),
                (
                    "smtp_from_name",
                    models.CharField(
                        blank=True,
                        help_text="留空使用全局配置",
                        max_length=255,
                        null=True,
                        verbose_name="发件人名称",
                    ),
                ),
                (
                    "captcha_provider",
                    models.CharField(
                        blank=True,
                        choices=[("none", "无"), ("tianai", "天爱验证码")],
                        help_text="留空使用全局配置",
                        max_length=32,
                        null=True,
                        verbose_name="验证码提供器",
                    ),
                ),
                (
                    "captcha_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLIDER", "滑块验证"),
                            ("ROTATE", "旋转验证"),
                            ("CONCAT", "滑动还原"),
                            ("WORD_IMAGE_CLICK", "文字点选"),
                        ],
                        help_text="留空使用全局配置",
                        max_length=32,
                        null=True,
                        verbose_name="默认验证码类型",
                    ),
                ),
                (
                    "login_captcha_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLIDER", "滑块验证"),
                            ("ROTATE", "旋转验证"),
                            ("CONCAT", "滑动还原"),
                            ("WORD_IMAGE_CLICK", "文字点选"),
                        ],
                        help_text="留空使用全局配置",
                        max_length=32,
                        null=True,
                        verbose_name="登录验证码类型",
                    ),
                ),
                (
                    "register_captcha_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLIDER", "滑块验证"),
                            ("ROTATE", "旋转验证"),
                            ("CONCAT", "滑动还原"),
                            ("WORD_IMAGE_CLICK", "文字点选"),
                        ],
                        help_text="留空使用全局配置",
                        max_length=32,
                        null=True,
                        verbose_name="注册验证码类型",
                    ),
                ),
                (
                    "email_captcha_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLIDER", "滑块验证"),
                            ("ROTATE", "旋转验证"),
                            ("CONCAT", "滑动还原"),
                            ("WORD_IMAGE_CLICK", "文字点选"),
                        ],
                        help_text="留空使用全局配置",
                        max_length=32,
                        null=True,
                        verbose_name="邮箱验证码类型",
                    ),
                ),
                (
                    "enable_registration",
                    models.BooleanField(
                        blank=True,
                        help_text="留空使用全局配置",
                        null=True,
                        verbose_name="启用用户注册",
                    ),
                ),
                (
                    "email_suffix_whitelist",
                    models.TextField(
                        blank=True,
                        help_text="留空使用全局配置。每行一个后缀",
                        null=True,
                        verbose_name="邮箱后缀白名单",
                    ),
                ),
                (
                    "email_suffix_blacklist",
                    models.TextField(
                        blank=True,
                        help_text="留空使用全局配置。每行一个后缀",
                        null=True,
                        verbose_name="邮箱后缀黑名单",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "site_group",
                    models.OneToOneField(
                        help_text="关联的站点组",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="dashboard.sitegroup",
                        verbose_name="站点组",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点组配置",
                "verbose_name_plural": "站点组配置",
            },
        ),
    ]
