# Generated by Django 4.2.27 on 2026-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_sitegroupconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitegroupconfig",
            name="icp_number",
            field=models.CharField(
                blank=True,
                help_text="留空使用全局配置",
                max_length=100,
                null=True,
                verbose_name="ICP备案号",
            ),
        ),
        migrations.AddField(
            model_name="sitegroupconfig",
            name="police_number",
            field=models.CharField(
                blank=True,
                help_text="留空使用全局配置",
                max_length=100,
                null=True,
                verbose_name="公安备案号",
            ),
        ),
        migrations.AddField(
            model_name="sitegroupconfig",
            name="site_icon",
            field=models.CharField(
                blank=True,
                help_text="留空使用全局配置。图标路径，如 /media/branding/icon.svg",
                max_length=500,
                null=True,
                verbose_name="站点图标",
            ),
        ),
        migrations.AddField(
            model_name="sitegroupconfig",
            name="site_name",
            field=models.CharField(
                blank=True,
                help_text="留空使用全局配置",
                max_length=100,
                null=True,
                verbose_name="站点名称",
            ),
        ),
    ]
