# Generated by Django 4.2.27 on 2026-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_sitegroupconfig_icp_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="site_icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="站点图标路径，如 /media/branding/icon.svg，留空使用默认图标",
                max_length=500,
                verbose_name="站点图标",
            ),
        ),
    ]
