# Generated by Django 4.2.27 on 2026-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_sitegroup_sitegrouphostname_and_more"),
        ("accounts", "0007_add_registrationlink_max_uses"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="site_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="用户所属的站点组，决定用户可见的数据范围",
                related_name="members",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
    ]
