# Generated by Django 4.2.27 on 2026-06-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_site_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="绑定的邮箱地址",
                        max_length=254,
                        verbose_name="邮箱地址",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="是否为用户的主邮箱",
                        verbose_name="主邮箱",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="邮箱是否已通过验证码验证",
                        verbose_name="已验证",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="邮箱绑定的时间",
                        verbose_name="绑定时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="关联的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户邮箱",
                "verbose_name_plural": "用户邮箱",
                "indexes": [
                    models.Index(fields=["email"], name="accounts_us_email_37c5c6_idx"),
                    models.Index(
                        fields=["user", "is_primary"],
                        name="accounts_us_user_id_664fe0_idx",
                    ),
                ],
                "unique_together": {("email",)},
            },
        ),
    ]
