# Generated by Django 4.2.27 on 2026-06-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_useremail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="封禁理由")),
                ("banned_at", models.DateTimeField(verbose_name="封禁时间")),
                (
                    "unbanned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="解封时间"),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_ban_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="封禁操作者",
                    ),
                ),
                (
                    "unbanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_ban_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解封操作者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "封禁历史",
                "verbose_name_plural": "封禁历史",
                "ordering": ["-unbanned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="封禁该用户的理由，将展示给用户",
                        verbose_name="封禁理由",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="封禁操作的时间",
                        verbose_name="封禁时间",
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="执行封禁操作的管理员",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_bans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="封禁操作者",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="被封禁的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_ban",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户封禁",
                "verbose_name_plural": "用户封禁",
            },
        ),
    ]
