# Generated by Django 4.2.30 on 2026-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificateauthority_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcertificate',
            name='upn_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='UPN值'),
        ),
        migrations.AddField(
            model_name='servercertificate',
            name='_pfx_password',
            field=models.CharField(blank=True, db_column='pfx_password', default='', max_length=255, verbose_name='PFX密码(加密)'),
        ),
        migrations.AddField(
            model_name='servercertificate',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
    ]
