# Generated by Django 4.2.30 on 2026-05-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_migrate_to_ecc_p256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcertificate',
            name='_private_key',
        ),
        migrations.RemoveField(
            model_name='clientcertificate',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='servercertificate',
            name='_pfx_password',
        ),
        migrations.RemoveField(
            model_name='servercertificate',
            name='_private_key',
        ),
        migrations.RemoveField(
            model_name='servercertificate',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='servercertificate',
            name='pfx_data',
        ),
    ]
