# Generated by Django 4.2.30 on 2026-05-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_host_auth_method_host_cert_key_path_and_more'),
        ('bootstrap', '0008_add_pairing_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialtoken',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联的主机'),
        ),
    ]
