# Generated by Django 4.2.30 on 2026-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0009_initialtoken_host_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialtoken',
            name='cert_data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='暂存证书数据'),
        ),
    ]
