# Generated by Django 4.2.30 on 2026-05-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_host_username_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bootstrap', '0010_add_cert_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertProvisionToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='配置令牌')),
                ('server_host', models.CharField(max_length=255, verbose_name='服务器地址')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('status', models.CharField(choices=[('ISSUED', '已签发'), ('HOSTNAME_UPLOADED', '主机名已上传'), ('CERT_ISSUED', '证书已签发'), ('HOST_CONFIGURED', '主机已配置'), ('CONSUMED', '已消耗')], default='ISSUED', max_length=20, verbose_name='状态')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消耗时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.host', verbose_name='关联的主机')),
            ],
            options={
                'verbose_name': '证书配置令牌',
                'verbose_name_plural': '证书配置令牌',
                'db_table': 'cert_provision_token',
            },
        ),
    ]
