# Generated by Django 4.2.30 on 2026-05-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0011_add_cert_provision_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='certprovisiontoken',
            name='cert_data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='暂存证书数据'),
        ),
        migrations.AddField(
            model_name='certprovisiontoken',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='主机名'),
        ),
    ]
