# Generated by Django 4.2.27 on 2026-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_add_group_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="allow_banned_users",
            field=models.BooleanField(
                default=False,
                help_text="封禁用户是否可以在此分类下提交工单",
                verbose_name="允许封禁用户提交",
            ),
        ),
    ]
