# Generated by Django 4.2.27 on 2026-06-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0019_alter_product_site_group_and_more"),
        ("tickets", "0004_ticketcategory_allow_banned_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="related_host",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="related_product",
        ),
        migrations.AddField(
            model_name="ticket",
            name="related_cloud_computer",
            field=models.ForeignKey(
                blank=True,
                help_text="工单关联的我拥有的云电脑",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="operations.cloudcomputeruser",
                verbose_name="关联云电脑",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="related_request",
            field=models.ForeignKey(
                blank=True,
                help_text="工单关联的我提交的申请",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="operations.accountopeningrequest",
                verbose_name="关联申请",
            ),
        ),
    ]
