# Generated by Django 4.2.30 on 2026-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_encrypt_initial_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdpdomainroute',
            name='domain',
            field=models.CharField(help_text='分配给用户的临时RDP访问域名（仅用于显示/追踪，不再用于SNI路由）', max_length=255, unique=True, verbose_name='RDP域名'),
        ),
        migrations.AlterField(
            model_name='rdpdomainroute',
            name='tunnel_token',
            field=models.CharField(blank=True, help_text='关联主机的隧道Token，用于RD Gateway路由', max_length=64, verbose_name='隧道Token'),
        ),
    ]
