# Generated by Django 4.2.27 on 2026-05-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0016_add_product_limit_one_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="管理员重试开户的次数", verbose_name="重试次数"
            ),
        ),
    ]
