# Generated by Django 4.2.27 on 2026-05-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_sitegroup_sitegrouphostname_and_more"),
        ("operations", "0017_accountopeningrequest_retry_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                help_text="该产品所属的站点组，留空表示默认组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                help_text="该产品组所属的站点组，留空表示默认组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_groups",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
    ]
