# Generated by Django 4.2.30 on 2026-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_remove_host_host_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='auth_method',
            field=models.CharField(choices=[('ntlm', '管理员账户密码'), ('certificate', '证书')], default='ntlm', max_length=20, verbose_name='连接方式'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_key_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='客户端私钥路径'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_pem_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='客户端证书路径'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('windows', 'Windows')], default='windows', max_length=20, verbose_name='主机系统'),
        ),
        migrations.AlterField(
            model_name='host',
            name='connection_type',
            field=models.CharField(choices=[('winrm', 'WinRM'), ('localwinserver', '本地WinServer'), ('ssh', 'SSH'), ('tunnel', '隧道模式(零公网IP)')], default='winrm', max_length=20, verbose_name='连接类型'),
        ),
    ]
