# Generated by Django 4.2.30 on 2026-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_host_auth_method_host_cert_key_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='用户名'),
        ),
    ]
