# Generated by Django 4.2.30 on 2026-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_host_username_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='_ntlm_fallback_password',
            field=models.CharField(blank=True, db_column='ntlm_fallback_password', default='', max_length=255, verbose_name='NTLM回退密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='_pfx_password',
            field=models.CharField(blank=True, db_column='pfx_password', default='', max_length=255, verbose_name='PFX密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='证书激活时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_provision_status',
            field=models.CharField(choices=[('not_started', '未开始'), ('pending', '签发中'), ('ready', '已就绪'), ('configured', '已配置'), ('failed', '失败')], default='not_started', max_length=20, verbose_name='证书配置状态'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_root',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='证书存储根路径'),
        ),
        migrations.AddField(
            model_name='host',
            name='cert_sub',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='证书存储子路径'),
        ),
        migrations.AddField(
            model_name='host',
            name='ntlm_fallback_user',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NTLM回退用户名'),
        ),
    ]
