# Generated by Django 4.2.27 on 2026-05-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_sitegroup_sitegrouphostname_and_more"),
        ("hosts", "0013_add_cert_provision_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                help_text="该主机所属的站点组，留空表示默认组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosts",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
        migrations.AddField(
            model_name="hostgroup",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                help_text="该主机组所属的站点组，留空表示默认组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="host_groups",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
    ]
