# Generated by Django 4.2.27 on 2026-06-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_remove_sitegroup_dashboard_s_slug_5cb7f5_idx_and_more"),
        ("hosts", "0014_host_site_group_hostgroup_site_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosts",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
        migrations.AlterField(
            model_name="hostgroup",
            name="site_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="host_groups",
                to="dashboard.sitegroup",
                verbose_name="所属站点组",
            ),
        ),
    ]
